language: ruby
rvm:
  - 2.7.8
env:
  - GEM=rao-api-resources_controller
  - GEM=rao-api-service_controller
  - GEM=rao-component
  - GEM=rao-query
  - GEM=rao-resource_controller
  - GEM=rao-resources_controller
  - GEM=rao-service
  - GEM=rao-service_chain
  - GEM=rao-service_controller
  - GEM=rao-shoulda_matchers
  - GEM=rao-view_helper
before_script:
  - gem update --system
  - gem install bundler --version="~> 2"
script: ./rspec.sh