source "https://rubygems.org"
gemspec
gem "rao", path: "../"
gem "rails", "8.0.2"

# source "https://rubygems.org"
# 
# # Specify your gem's dependencies in rao-component.gemspec.
# gemspec
# 
# gem "rails", git: "https://github.com/rails/rails.git", branch: "main"
# 
# gem "puma"
# 
# gem "sqlite3"
# 
# gem "propshaft"
# 
# # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
# gem "rubocop-rails-omakase", require: false
# 
# # Start debugger with binding.b [https://github.com/ruby/debug]
# # gem "debug", ">= 1.0.0"
